# Generated by Django 3.2.6 on 2021-08-08 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokedexVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pokedex_id', models.PositiveIntegerField()),
                ('sprite', models.ImageField(upload_to='sprite/')),
                ('height', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('type_one', models.CharField(max_length=255)),
                ('type_two', models.CharField(max_length=255)),
                ('health_points', models.CharField(max_length=255)),
                ('attack', models.CharField(max_length=255)),
                ('defence', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='pokemonVersionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokedexversion')),
            ],
        ),
    ]
